### ISSUE TITLE
index.jade

### ISSUE THREAD

**Issue by samurai-jack** [PEM--/pdfrenderer#1]
Great package and article http://pem-musing.blogspot.fr/2015/06/pdf-your-collections-client-side.html. My question is whether you can get your pdfrenderer / app / client / index.jade as index.html, because I'm not able to read properly code.

Thank you

**Comment by PEM--** [comment]
Which part did you not get? I'm very dumb at raw Blaze not having used it since a long time.

**Comment by samurai-jack** [comment]
template(name='svgTest')
  button PDF
  hr
  if Template.subscriptionsReady
    with customer
      h1= name
      with address
        p= street
        p= city
    with table
      table
        thead
          tr
            th= tableName
            each labels
              th= this
        tbody
          each lines
            tr
              each this
                td= this
  else
    p Loading...
  hr
  svg.chart

**Comment by samurai-jack** [comment]
``` javascript
  if Template.subscriptionsReady
    with customer
      h1= name
      with address
        p= street
        p= city
    with table
      table
        thead
          tr
            th= tableName
            each labels
              th= this
        tbody
          each lines
            tr
              each this
                td= this
  else
    p Loading...
  hr
  svg.chart
```

**Comment by PEM--** [comment]
Wow, you mean almost everything...

Basically, it's a Blaze template named `svgTest`. It has a simple button that I use in CS for launching the PDF rendering. This template has subscription which shows an `h1` tag and a `table`. This template also contains an empty `svg` tag on which I'm setting a little chart with D3.

**Comment by samurai-jack** [comment]
Thank you
